export const cityResponseData = {
  data: [
    {
      id: 659,
      wikiDataId: 'Q1519',
      type: 'CITY',
      city: 'Abu Dhabi',
      name: 'Abu Dhabi',
      country: 'United Arab Emirates',
      countryCode: 'AE',
      region: 'Abu Dhabi Emirate',
      regionCode: 'AZ',
      latitude: 24.478055555,
      longitude: 54.368611111,
    },
    {
      id: 466804,
      type: 'ADM2',
      city: 'Abu Dhabi Municipality',
      name: 'Abu Dhabi Municipality',
      country: 'United Arab Emirates',
      countryCode: 'AE',
      region: 'Abu Dhabi Emirate',
      regionCode: 'AZ',
      latitude: 24.41361,
      longitude: 54.43295,
    },
    {
      id: 638,
      wikiDataId: 'Q530171',
      type: 'CITY',
      city: 'Ajman',
      name: 'Ajman',
      country: 'United Arab Emirates',
      countryCode: 'AE',
      region: 'Ajman Emirate',
      regionCode: 'AJ',
      latitude: 25.399444444,
      longitude: 55.479722222,
    },
    {
      id: 644,
      wikiDataId: 'Q234600',
      type: 'CITY',
      city: 'Al Ain',
      name: 'Al Ain',
      country: 'United Arab Emirates',
      countryCode: 'AE',
      region: 'Abu Dhabi Emirate',
      regionCode: 'AZ',
      latitude: 24.2075,
      longitude: 55.744722222,
    },
    {
      id: 466805,
      type: 'ADM2',
      city: 'Al Ain Municipality',
      name: 'Al Ain Municipality',
      country: 'United Arab Emirates',
      countryCode: 'AE',
      region: 'Abu Dhabi Emirate',
      regionCode: 'AZ',
      latitude: 24.15223,
      longitude: 55.8204,
    },
  ],
};
